const getFlag = (countryCode: string): string =>
  String.fromCodePoint(
    ...countryCode
      .split('')
      .map((letter) => 127397 + letter.toUpperCase().charCodeAt(0))
  );

export const getCurrencies = () => {
  const currencies: {name: string; value: string; flag: string}[] = [
    {name: 'SATS', value: 'sats', flag: '₿'},
    {name: 'BTC', value: 'BTC', flag: '₿'},
    {name: 'USD', value: 'USD', flag: getFlag('US')},
    {name: 'EUR', value: 'EUR', flag: '🇪🇺'},
  ];

  // Cleaned up list from https://github.com/annexare/Countries
  const ISOMapping = {
    JP: 'JPY',
    CN: 'CNY',
    GB: 'GBP',
    CH: 'CHF',
    IN: 'INR',
    AE: 'AED',
    AF: 'AFN',
    AL: 'ALL',
    DZ: 'DZD',
    AO: 'AOA',
    AR: 'ARS',
    AM: 'AMD',
    AW: 'AWG',
    AU: 'AUD',
    AZ: 'AZN',
    BS: 'BSD',
    BH: 'BHD',
    BD: 'BDT',
    BB: 'BBD',
    BY: 'BYN',
    BZ: 'BZD',
    BM: 'BMD',
    BT: 'BTN',
    BO: 'BOB',
    BA: 'BAM',
    BW: 'BWP',
    BR: 'BRL',
    BN: 'BND',
    BG: 'BGN',
    BI: 'BIF',
    CV: 'CVE',
    KH: 'KHR',
    CA: 'CAD',
    KY: 'KYD',
    CF: 'XAF',
    CL: 'CLP',
    CO: 'COU',
    KM: 'KMF',
    CD: 'CDF',
    CR: 'CRC',
    CU: 'CUC',
    CW: 'ANG',
    CZ: 'CZK',
    DK: 'DKK',
    DJ: 'DJF',
    DM: 'XCD',
    DO: 'DOP',
    EG: 'EGP',
    ER: 'ERN',
    ET: 'ETB',
    FJ: 'FJD',
    PF: 'XPF',
    GM: 'GMD',
    GE: 'GEL',
    GH: 'GHS',
    GI: 'GIP',
    GT: 'GTQ',
    GN: 'GNF',
    GY: 'GYD',
    HN: 'HNL',
    HK: 'HKD',
    HU: 'HUF',
    IS: 'ISK',
    ID: 'IDR',
    IR: 'XDR',
    IQ: 'IQD',
    IL: 'ILS',
    JM: 'JMD',
    JO: 'JOD',
    KZ: 'KZT',
    KE: 'KES',
    KR: 'KRW',
    KW: 'KWD',
    KG: 'KGS',
    LA: 'LAK',
    LB: 'LBP',
    LR: 'LRD',
    LY: 'LYD',
    MO: 'MOP',
    MG: 'MGA',
    MW: 'MWK',
    MY: 'MYR',
    MV: 'MVR',
    MR: 'MRU',
    MU: 'MUR',
    MX: 'MXN',
    MD: 'MDL',
    MN: 'MNT',
    MA: 'MAD',
    MZ: 'MZN',
    MM: 'MMK',
    NP: 'NPR',
    NZ: 'NZD',
    NI: 'NIO',
    NE: 'XOF',
    NG: 'NGN',
    MK: 'MKD',
    NO: 'NOK',
    OM: 'OMR',
    PK: 'PKR',
    PG: 'PGK',
    PY: 'PYG',
    PE: 'PEN',
    PH: 'PHP',
    PL: 'PLN',
    QA: 'QAR',
    RO: 'RON',
    RU: 'RUB',
    RW: 'RWF',
    SH: 'SHP',
    WS: 'WST',
    ST: 'STN',
    SA: 'SAR',
    RS: 'RSD',
    SC: 'SCR',
    SL: 'SLL',
    SG: 'SGD',
    SB: 'SBD',
    SO: 'SOS',
    ZA: 'ZAR',
    SS: 'SSP',
    LK: 'LKR',
    SD: 'SDG',
    SR: 'SRD',
    SE: 'SEK',
    SY: 'SYP',
    TW: 'TWD',
    TJ: 'TJS',
    TZ: 'TZS',
    TH: 'THB',
    TO: 'TOP',
    TT: 'TTD',
    TN: 'TND',
    TR: 'TRY',
    TM: 'TMT',
    UG: 'UGX',
    UA: 'UAH',
    UY: 'UYU',
    UZ: 'UZS',
    VU: 'VUV',
    VN: 'VND',
    YE: 'YER',
    ZM: 'ZMW',
    ZW: 'ZWL',
  };
  currencies.push(
    ...Object.entries(ISOMapping).map(([name, value]) => ({
      name,
      value,
      flag: getFlag(name),
    }))
  );
  return currencies;
};
